apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server-deployment
  labels:
    app: oauth-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oauth-server
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      serviceAccountName: oauth-server-service-account
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: oauth-server
          image: {{ lower .Values.ImageCredentials.Registry }}/{{ lower .Values.ImageCredentials.Username }}/{{ .Values.GitHub.Container.Image }}:{{ lower .Values.GitHub.Container.Tag }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              scheme: 'HTTPS'
              path: /api/health-check/status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: COOKIE_SECRETS
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: cookieSecrets
            - name: NODE_ENV
              value: production
            - name: ISSUER
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: issuer
            - name: ACCESS_JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: accessTokenSecret
            - name: ACCESS_JWT_EXPIRY
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: accessTokenExpiry
            - name: REFRESH_JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: refreshTokenSecret
            - name: REFRESH_JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: oauth-server-config-map
                  key: refreshTokenExpiry
            - name: ENCRYPTION_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: encryptionSecret
            - name: ENCRYPTION_SECRET_IV
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: encryptionSecretIV
            - name: ENCRYPTION_METHOD
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: encryptionMethod
            - name: EMAIL_SERVICE
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: emailService
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: emailAddress
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: emailPassword
            - name: AWS_REGION
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: awsRegion
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: awsKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: awsSecret
