apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server-deployment
  namespace: oauth
  labels:
    app: oauth-server
spec:
  serviceAccountName: oauth-server-dynamob-service-account
  replicas: 2
  selector:
    matchLabels:
      app: oauth-server
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: oauth-server
          image: {{ .Values.ImageCredentials.Registry }}/{{ .Values.ImageCredentials.Username }}/{{ .Values.GitHub.Container.Image }}:{{ .Values.GitHub.Container.Tag }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: COOKIE_SECRETS
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: cookieSecrets
            - name: NODE_ENV
              value: production
            - name: ISSUER
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: issuer
            - name: ACCESS_JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: accessTokenSecret
            - name: ACCESS_JWT_EXPIRY
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: accessTokenExpiry
            - name: REFRESH_JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: refreshTokenSecret
            - name: REFRESH_JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: oauth-server-config-map
                  key: refreshTokenExpiry
            - name: ENCRYPTION_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: encryptionSecret
            - name: ENCRYPTION_SECRET_IV
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: encryptionSecretIV
            - name: ENCRYPTION_METHOD
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: encryptionMethod
            - name: EMAIL_SERVICE
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: emailService
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef: 
                  name: oauth-server-config-map
                  key: emailAddress
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: oauth-server-secret
                  key: emailPassword
