apiVersion: v1
kind: Secret
metadata:
  name: oauth-server-secret
type: "Opaque"
data:
  containerRegistrySecret:
    {{ .Values.GitHub.ContainerRegistrySecret | b64enc }}
  accessTokenSecret:
    {{ .Values.Server.Authentication.accessTokenSecret | b64enc }}
  refreshTokenSecret:
    {{ .Values.Server.Authentication.refreshTokenSecret | b64enc }}
  encryptionSecret: {{ .Values.Server.Encryption.Secret | b64enc }}
  encryptionSecretIV: {{ .Values.Server.Encryption.SecretIV | b64enc }}
  emailPassword: {{ .Values.Server.Email.EmailPassword | b64enc }}
