apiVersion: v1
kind: Secret
metadata:
  name: oauth-server-secret
type: "Opaque"
data:
  containerRegistrySecret:
  cookieSecrets: |-
    {{- range .Values.Server.CookieSecrets }}
      - {{ . | b64enc }}
    {{- end }}  
  accessTokenSecret:
    {{ .Values.Server.Authentication.accessTokenSecret | quote | b64enc }}
  refreshTokenSecret:
    {{ .Values.Server.Authentication.refreshTokenSecret | quote | b64enc }}
  encryptionSecret: {{ .Values.Server.Encryption.Secret | quote | b64enc }}
  encryptionSecretIV: {{ .Values.Server.Encryption.SecretIV | quote | b64enc }}
  emailPassword: {{ .Values.Server.Email.EmailPassword | quote | b64enc }}
