apiVersion: v1
kind: Secret
metadata:
  name: oauth-server-secret
type: "Opaque"
data:
  cookieSecrets: {{ join ","  .Values.Server.CookieSecrets | b64enc }}
  accessTokenSecret:
    {{ .Values.Server.Authentication.AccessTokenSecret | b64enc }}
  refreshTokenSecret:
    {{ .Values.Server.Authentication.RefreshTokenSecret | b64enc }}
  encryptionSecret: {{ .Values.Server.Encryption.Secret | b64enc }}
  encryptionSecretIV: {{ .Values.Server.Encryption.SecretIV | b64enc }}
  emailPassword: {{ .Values.Server.Email.EmailPassword | b64enc }}
