apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth-server-lb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name: oauth-server-lb
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}]'
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: oauth-server-service
      port:
        number: 443
