apiVersion: v1
kind: Service
metadata:
  name: oauth-server-service
spec:
  selector:
    app: oauth-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      nodePort: 30080
