apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-server-config-map
data:
  issuer: {{ .Values.Server.Authentication.Issuer }}
  accessTokenExpiry: {{ .Values.Server.Authentication.AccessTokenExpiry }}
  refreshTokenExpiry: {{ .Values.Server.Authentication.RefreshTokenExpiry }}
  encryptionMethod: {{ .Values.Server.Encryption.Method }}
  emailService: {{ .Values.Server.Email.Service }}
  emailAddress: {{ .Values.Server.Email.EmailAddress }}
