name: Deploy OAuth Server
on:
  workflow_dispatch:

jobs:
  provision-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Setup Open Tofu
        uses: opentofu/setup-opentofu@v1
      - name: Provision recipe lambda & website
        working-directory: "./infra"
        run: |
          tofu init --backend-config="bucket=${{vars.AWS_TERRAFORM_STATE_BUCKET_NAME}}" --backend-config="key=${{vars.AWS_TERRAFORM_STATE_KEY}}.tfstate"
          tofu apply -auto-approve
        env:
          TF_VAR_aws_access_key: "${{secrets.AWS_ACCESS_KEY_ID}}"
          TF_VAR_aws_secret_key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
      - name: Install AWS CLI and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Generate KUBECONFIG for EKS
        run: |
          aws eks update-kubeconfig --name oauth-server-cluster --region eu-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Helm Deploy OAuth Server
        run: |
          helm upgrade --install oauth-server ./helm \
            --set image.repository=my-oauth-server-image \
            --set image.tag=latest \
            --set service.type=LoadBalancer