name: Build OAuth Server Artefact
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      fail-fast: false
      matrix:
        component:
          - backend
          - frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: "run ${{matrix.component}} unit tests"
        working-directory: "./packages/${{matrix.component}}"
        run: |
          npm ci
          npm run test:unit
  build:
    name: Build & push docker image
    needs: unit-tests
    runs-on: ubuntu-latest
    environment: Production
    env:
      IMG_NAME: "ghcr.io/${{ github.repository }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
